### ISSUE TITLE
Extra fields not permitted

### ISSUE THREAD

**Issue by ongolaboy** [thatmattlove/hyperglass#172]
# Bug Description

Hi,
when running `hyperglass build-ui` I get several warning and an error.
Execute `hyperglass build-ui`  after setup

# Expected behavior

Being able to customize hyperglass after this step.

# Steps to Reproduce

On a minimal debian 11 install,
1. Install: python3-distutils python3-pip python3-dev libjpeg-dev
2. run curl https://install.hyperglass.dev | bash
3. execute `hyperglass setup`
4. edit two files: hyperglass.yaml, devices.yaml
5. run `hyperglass build-ui`

## Local Configurations

hyperglass.yaml
```
debug: false
developer_mode: false
primary_asn: 'xxxx'
org_name: Corp1
site_title: hyperglass 1
site_description: "{org_name} Network Looking Glass"
site_keywords: [hyperglass, looking glass, routing, bgp]
request_timeout: 30
listen_address: "::1"
listen_port: 8001
log_file: /tmp/hyperglass.log
```

```
routers:
  - name: Border router
    address: my.FQDN
    network:
      name: production
      display_name: ASxxxx
    credential:
      username: marvellous
      key: /home/to.my/ssh.key
    port: 22
    nos: frr
    vrfs:
      - name: default
        default: true
        ipv4:
          source_address: my.IPv4.address
        ipv6:
          source_address: my.IPv6.address
```
## Logs

```
[WARNING] 20211123 09:52:59 | hyperglass.models.config.vrf:239 | set_dynamic → You have set the VRF name to 'default'. This is no longer the way to
designate a VRF as the default (or global routing table) VRF. Instead,
add 'default: true' to the VRF definition.

[INFO] 20211123 09:52:59 | hyperglass.configuration.main:39 | <module> → Configuration directory: /etc/hyperglass
Traceback (most recent call last):
[WARNING] 20211123 09:52:59 | hyperglass.configuration.main:65 | _check_config_files → '/etc/hyperglass/commands.yaml' was not found, but is not required to run hyperglass. Defaults will be used.
  File "/usr/local/bin/hyperglass", line 8, in <module>
    sys.exit(CLI())
[ERROR] 20211123 09:52:59 | hyperglass.configuration.validation:47 | validate_config → 1 validation error for Params
log_file
  extra fields not permitted (type=value_error.extra)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
[ERROR] 20211123 09:52:59 | hyperglass.exceptions:38 | __init__ → [WARNING]

Field: log_file
  Error: extra fields not permitted

  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/hyperglass/cli/commands.py", line 70, in build_frontend
    return build_ui(timeout)
  File "/usr/local/lib/python3.9/dist-packages/hyperglass/cli/util.py", line 68, in build_ui
    from hyperglass.configuration import CONFIG_PATH, params, frontend_params
  File "/usr/local/lib/python3.9/dist-packages/hyperglass/configuration/__init__.py", line 4, in <module>
    from .main import (
  File "/usr/local/lib/python3.9/dist-packages/hyperglass/configuration/main.py", line 120, in <module>
    params = validate_config(config=user_config, importer=Params)
  File "/usr/local/lib/python3.9/dist-packages/hyperglass/configuration/validation.py", line 48, in validate_config
    raise ConfigInvalid(err.errors()) from None
hyperglass.exceptions.ConfigInvalid:

Field: log_file
  Error: extra fields not permitted
```

# Possible Solution

# Environment

## Server

| Metric | Value |
| ------ | ----- |
| **hyperglass Version** | **1.0.0** |
| **hyperglass Path** | `/etc/hyperglass` |
| **Python Version** | `3.9.2` |
| **Platform Info** | `Linux-5.10.0-9-amd64-x86_64-with-glibc2.31` |
| **CPU Info** | QEMU Virtual CPU version 2.5+ |
| **Logical Cores** | `2` |
| **Physical Cores** | `2` |
| **Processor Speed** | 1.8999970000000002GHz |
| **Total Memory** | 4.12 GB |
| **Memory Utilization** | 7.9% |
| **Total Disk Space** | 9.45 GB |
| **Disk Utilization** | 24.5% |

**Comment by thatmattlove** [comment]
Hello,

`log_file` is no longer how logging is configured, see [here](https://hyperglass.dev/docs/logging) for logging options. You should be able to simply delete the `log_file` line.

I do see that the example from the docs still includes this, I'll get that removed.
