### ISSUE TITLE
Error in bgp_router query on Huawei

### ISSUE THREAD

**Issue by arraisfilho** [thatmattlove/hyperglass#187]
In Huawei it is necessary to have a space after the slash "1.1.1.0 24", by the logs, this treatment is not happening.   

```
[DEBUG] 20220128 01:01:14 | hyperglass.execution.drivers._construct:27 | __init__ → Constructing bgp_route query for '1.1.1.0/24'
[DEBUG] 20220128 01:01:14 | hyperglass.execution.drivers._construct:111 | queries → Constructed query: ['display bgp routing-table 1.1.1.0/24']
[DEBUG] 20220128 01:01:14 | hyperglass.execution.drivers.ssh_netmiko:57 | collect → Connecting directly to São Paulo, SP, Brasil
[DEBUG] 20220128 01:01:18 | hyperglass.execution.drivers.ssh_netmiko:103 | collect → Raw response for command "display bgp routing-table 1.1.1.0/24":
                                        ^
Error: Wrong parameter found at '^' position.
[DEBUG] 20220128 01:01:18 | hyperglass.execution.drivers._common:34 | parsed_response → Pre-parsed responses:
("                                        ^\nError: Wrong parameter found at '^' position.",)
[DEBUG] 20220128 01:01:18 | hyperglass.execution.drivers._common:80 | parsed_response → Post-parsed responses:
^
Error: Wrong parameter found at '^' position.
```

Up to version 1.0.0, this treatment is performed, according to the logs below.

```
[DEBUG] 20220128 00:44:52 | hyperglass.execution.drivers._construct:36 | __init__ → Constructing bgp_route query for '1.1.1.0/24'
[DEBUG] 20220128 00:44:52 | hyperglass.execution.drivers._construct:160 | queries → Constructed query: ['display bgp routing-table 1.1.1.0 24']
[DEBUG] 20220128 00:44:52 | hyperglass.execution.drivers.ssh_netmiko:57 | collect → Connecting directly to São Paulo, SP, Brasil
```

Best Regards

**Comment by dd1245** [comment]
I have this same issue. Ping commands and traceroute work fine, but the command issued for the routing table is incorrect as already mentioned.

As per the example, display bgp routing-table 1.1.1.0/24 needs to be display bgp routing-table 1.1.1.0 24

What is the best way to address this?

**Comment by jakeb91** [comment]
I suspect this is being caused by the addition of the `Formatter` class in `execution/drivers/_construct.py` - this is a new addition in 1.0.4 that wasn't present in 1.0.0

Specifically - you can see that the formatting override for `huawei` and `huawei_vrpv8` are ignored because the `Formatter` class references the original query target, rather than the corrected query target. 

Line 39-40 in execution/drivers/_construct.py - where the query target is corrected.
```
        if self.device.nos in TARGET_FORMAT_SPACE:
            self.target = re.sub(r"\/", r" ", str(self.query_data.query_target))
```

Line 67-68 in execution/drivers/_construct.py - where the corrected query target is ignored and the original data is referenced and replaces the corrected query target with the uncorrected version.
```
        with Formatter(self.device.nos, self.query_data.query_type) as formatter:
            self.target = formatter(self.query_data.query_target)
```

**Comment by jakeb91** [comment]
Further to the above - I don't have environment to test this in (so I don't want to create a pull request), but adding the following code to `_construct.py` may work - or at-least this is a starting point.

Delete or comment out the following lines (Line 39-40):
```
        if self.device.nos in TARGET_FORMAT_SPACE:
            self.target = re.sub(r"\/", r" ", str(self.query_data.query_target))
```

Add the following to def _get_formatter(self) in the Formatter class:
```
	if self.nos in TARGET_FORMAT_SPACE:
		if self.query_type == "bgp_route":
			return self._huawei_bgp_route
```

Add the following to the Formatter class				
```
def _huawei_bgp_route(self, target: str) -> str:
	""" Remove slashes from target for required platforms."""
	self.target = re.sub(r"\/", r" ", str(self.query_data.query_target))
	log.debug("Modified target '{}' to '{}'", self.query_data.query_target, self.target)
	return query
```

**Comment by arraisfilho** [comment]
Hi @[jakeb91](https://github.com/jakeb91), did not work, the error below is the result when starting the Hyperglass service.

Traceback (most recent call last):
  File "/usr/local/bin/hyperglass", line 11, in <module>
    sys.exit(CLI())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/hyperglass/cli/commands.py", line 98, in start
    from hyperglass.api import start as uvicorn_start
  File "/usr/local/lib/python3.6/dist-packages/hyperglass/api/__init__.py", line 22, in <module>
    from hyperglass.api.routes import (
  File "/usr/local/lib/python3.6/dist-packages/hyperglass/api/routes.py", line 24, in <module>
    from hyperglass.execution.main import execute
  File "/usr/local/lib/python3.6/dist-packages/hyperglass/execution/main.py", line 20, in <module>
    from .drivers import Connection, AgentConnection, NetmikoConnection, ScrapliConnection
  File "/usr/local/lib/python3.6/dist-packages/hyperglass/execution/drivers/__init__.py", line 4, in <module>
    from .agent import AgentConnection
  File "/usr/local/lib/python3.6/dist-packages/hyperglass/execution/drivers/agent.py", line 24, in <module>
    from ._common import Connection
  File "/usr/local/lib/python3.6/dist-packages/hyperglass/execution/drivers/_common.py", line 14, in <module>
    from ._construct import Construct
  File "/usr/local/lib/python3.6/dist-packages/hyperglass/execution/drivers/_construct.py", line 129
    if self.nos in TARGET_FORMAT_SPACE:
                                      ^
TabError: inconsistent use of tabs and spaces in indentation

Regards

**Comment by rafamira2007** [comment]
For me it worked just editing the code below:

with Formatter(self.device.nos, self.query_data.query_type) as formatter:
            self.target = re.sub(r"\/", r" ", str(self.query_data.query_target))

**Comment by arraisfilho** [comment]
> For me it worked just editing the code below:
> 
> `with Formatter(self.device.nos, self.query_data.query_type) as formatter:` `self.target = re.sub(r"\/", r" ", str(self.query_data.query_target))`

What version are you on? 1.0.4?

I will alter it in /hyperglass/execution/drivers/__construct.py

    ```
Before
   with Formatter(self.device.nos, self.query_data.query_type) as formatter:
            self.target = formatter(self.query_data.query_target)
        
After    
        with Formatter(self.device.nos, self.query_data.query_type) as formatter:
            self.target = re.sub(r"\/", r" ", str(self.query_data.query_target))
```

The error below is returned. Has anything been tweaked or just what was mentioned?

Traceback (most recent call last):
  File "/usr/local/bin/hyperglass", line 11, in <module>
    sys.exit(CLI())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/hyperglass/cli/commands.py", line 98, in start
    from hyperglass.api import start as uvicorn_start
  File "/usr/local/lib/python3.6/dist-packages/hyperglass/api/__init__.py", line 22, in <module>
    from hyperglass.api.routes import (
  File "/usr/local/lib/python3.6/dist-packages/hyperglass/api/routes.py", line 24, in <module>
    from hyperglass.execution.main import execute
  File "/usr/local/lib/python3.6/dist-packages/hyperglass/execution/main.py", line 20, in <module>
    from .drivers import Connection, AgentConnection, NetmikoConnection, ScrapliConnection
  File "/usr/local/lib/python3.6/dist-packages/hyperglass/execution/drivers/__init__.py", line 4, in <module>
    from .agent import AgentConnection
  File "/usr/local/lib/python3.6/dist-packages/hyperglass/execution/drivers/agent.py", line 24, in <module>
    from ._common import Connection
  File "/usr/local/lib/python3.6/dist-packages/hyperglass/execution/drivers/_common.py", line 14, in <module>
    from ._construct import Construct
  File "/usr/local/lib/python3.6/dist-packages/hyperglass/execution/drivers/_construct.py", line 66
    with Formatter(self.device.nos, self.query_data.query_type) as formatter:
                                                                                                                              ^
IndentationError: unindent does not match any outer indentation level

**Comment by rafamira2007** [comment]
Edit on /hyperglass/execution/drivers/_construct.py and not /hyperglass/execution/drivers/__construct.py

only just make these changes

with Formatter(self.device.nos, self.query_data.query_type) as formatter:
               self.target = re.sub(r"\/", r" ", str(self.query_data.query_target))

Distro: Linux Debian 11 64Bits NetInstall
HyperGlass: Version 1.0.4

**Comment by allanfrizzo** [comment]
That way I was successful

Delete or comment out the following lines Line 39-40:

`if self.device.nos in TARGET_FORMAT_SPACE:
   self.target = re.sub(r"\/", r" ", str(self.query_data.query_target))`

Add the following to def _get_formatter(self) in the Formatter class:

`        if self.nos in TARGET_FORMAT_SPACE:
            if self.query_type == "bgp_route":
                return self._huawei_bgp_route`

Add the following to the Formatter class

`def _huawei_bgp_route(self, target: str) -> str:
        """ Remove slashes from target for required platforms."""
        self.target = re.sub(r"\/", r" ", str(target))
        log.debug("Modified target '{}' to '{}'", target, self.target)
        return self.target`

**Comment by remontti** [comment]
Above solutions did not work for me in real environment, the solution I found was:

```
         with Formatter(self.device.nos, self.query_data.query_type) as formatter:
            log.debug("==*HW*== '{}' to '{}'", self.device.nos, self.query_data.query_type)
            if self.device.nos in TARGET_FORMAT_SPACE:
                if self.query_data.query_type == "bgp_route":
                    self.target = re.sub(r"/", r" ", str(self.query_data.query_target))
                else:
                    self.target = formatter(self.query_data.query_target)
            else:
                self.target = formatter(self.query_data.query_target)

```

**Comment by jakeb91** [comment]
> Above solutions did not work for me in real environment, the solution I found was:
> 
> ```
>          with Formatter(self.device.nos, self.query_data.query_type) as formatter:
>             log.debug("==*HW*== '{}' to '{}'", self.device.nos, self.query_data.query_type)
>             if self.device.nos in TARGET_FORMAT_SPACE:
>                 if self.query_data.query_type == "bgp_route":
>                     self.target = re.sub(r"/", r" ", str(self.query_data.query_target))
>                 else:
>                     self.target = formatter(self.query_data.query_target)
>             else:
>                 self.target = formatter(self.query_data.query_target)
> ```

The related pull request has the working / fixed code - I don't have access to Huawei gear anymore though so I was unable to test it.

**Comment by emersonfelipesp** [comment]
I have the same issue here using `huawei_vrpv8`, the code just needs handle to remove the `/` from network prefix when the device is `Huawei`.

**Comment by thatmattlove** [comment]
Can anyone re-test this in v2 and list any changes that may be needed?

**Comment by gondimcodes** [comment]
Same problem with 2.0.4

**Comment by andrediashexa** [comment]
Unfortunately still not working. Looks like the code must do some king of string replace in {target}, replacing "/" to " ".

The problem is Huawei do not like when we send the command "display bgp routing-table 192.168.0.0/24" for example, as we must send "display bgp routing-table 192.168.0.0 24" to work.

Yes, Huawei likes to be different.

**Comment by remontti** [comment]
@gondimcodes @andrediashexa  edit **/opt/hyperglass/hyperglass/execution/drivers/_construct.py**

Adjust the function def __init__

```
    def __init__(self, device: "Device", query: "Query"):
        """Initialize command construction."""
        self._log = log.bind(type=query.query_type, target=query.query_target)
        self._log.debug("Constructing query")
        self.query = query
        self.device = device
        self.target = self.query.query_target
        self.directive = query.directive

        self.transport = "scrape"
        if self.device.platform in TRANSPORT_REST:
            self.transport = "rest"

        with Formatter(self.query) as formatter:
            prepared = self.prepare_target()
            if self.device.platform in TARGET_FORMAT_SPACE:
                self._log.debug("TARGET_FORMAT_SPACE (ON)")
                prepared = re.sub(r"/", " ", prepared)
            else:
                self._log.debug("TARGET_FORMAT_SPACE (OFF)")
            self.target = formatter(prepared)
```
